require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

RSpec/ExampleLength:
  Max: 10 # 5

Style/Documentation:
  Enabled: false
